services:
  # Serviço do Redis
  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 128M

  # Serviço do Banco de Dados
  db:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço de Setup do Banco de Dados
  db-setup:
    build: .
    container_name: db_setup
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run db:setup

  # Serviço dos Scrapers
  scraper-daily:
    build: .
    container_name: scraper_daily
    depends_on:
      db-setup:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run scrape:diario

  scraper-frequent:
    build: .
    container_name: scraper_frequent
    depends_on:
      db-setup:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run scrape:frequente

  # Serviço do Servidor Express
  app:
    build: .
    container_name: express_server
    restart: always
    ports:
      - "${V_PORT:-3001}:3001"
    depends_on:
      db-setup:
        condition: service_completed_successfully
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

volumes:
  pgdata: